export const RSSHubCategoryCopyMap = {
  all: "All",
  anime: "ACG",
  bbs: "BBS",
  blog: "Blog",
  design: "Design",
  finance: "Finance",
  forecast: "Forecast",
  game: "Gaming",
  government: "Government",
  journal: "Scientific Journal",
  live: "Live",
  multimedia: "Multimedia",
  "new-media": "New Media",
  picture: "Picture",
  "program-update": "Application Updates",
  programming: "Programming",
  reading: "Reading",
  shopping: "Shopping",
  "social-media": "Social Media",
  study: "Study",
  "traditional-media": "News",
  travel: "Travel",
  university: "University",
}
