policy:
  - section:
      - id: [platform]
        block-list: ["None", "Other"]
        label:
          - name: "platform: desktop"
            keys: ["Desktop - macOS", "Desktop - Windows", "Desktop - Linux", "Desktop - Web"]
          - name: "platform: mobile"
            keys: ["Mobile - iOS", "Mobile - Android", "Mobile - Web"]
