// This file is auto-generated by scripts/generate-i18n-locale.ts
// DONT EDIT THIS FILE MANUALLY
import common_ardz from "../../../desktop/locales/common/ar-DZ.json"
import common_ariq from "../../../desktop/locales/common/ar-IQ.json"
import common_arkw from "../../../desktop/locales/common/ar-KW.json"
import common_arma from "../../../desktop/locales/common/ar-MA.json"
import common_arsa from "../../../desktop/locales/common/ar-SA.json"
import common_artn from "../../../desktop/locales/common/ar-TN.json"
import common_de from "../../../desktop/locales/common/de.json"
import common_en from "../../../desktop/locales/common/en.json"
import common_es from "../../../desktop/locales/common/es.json"
import common_fi from "../../../desktop/locales/common/fi.json"
import common_fr from "../../../desktop/locales/common/fr.json"
import common_it from "../../../desktop/locales/common/it.json"
import common_ja from "../../../desktop/locales/common/ja.json"
import common_ko from "../../../desktop/locales/common/ko.json"
import common_pt from "../../../desktop/locales/common/pt.json"
import common_ru from "../../../desktop/locales/common/ru.json"
import common_tr from "../../../desktop/locales/common/tr.json"
import common_zhCN from "../../../desktop/locales/common/zh-CN.json"
import common_zhHK from "../../../desktop/locales/common/zh-HK.json"
import common_zhTW from "../../../desktop/locales/common/zh-TW.json"
import errors_en from "../../../desktop/locales/errors/en.json"
import external_en from "../../../desktop/locales/external/en.json"
import lang_ardz from "../../../desktop/locales/lang/ar-DZ.json"
import lang_ariq from "../../../desktop/locales/lang/ar-IQ.json"
import lang_arkw from "../../../desktop/locales/lang/ar-KW.json"
import lang_arma from "../../../desktop/locales/lang/ar-MA.json"
import lang_arsa from "../../../desktop/locales/lang/ar-SA.json"
import lang_artn from "../../../desktop/locales/lang/ar-TN.json"
import lang_de from "../../../desktop/locales/lang/de.json"
import lang_en from "../../../desktop/locales/lang/en.json"
import lang_es from "../../../desktop/locales/lang/es.json"
import lang_fi from "../../../desktop/locales/lang/fi.json"
import lang_fr from "../../../desktop/locales/lang/fr.json"
import lang_it from "../../../desktop/locales/lang/it.json"
import lang_ja from "../../../desktop/locales/lang/ja.json"
import lang_ko from "../../../desktop/locales/lang/ko.json"
import lang_pt from "../../../desktop/locales/lang/pt.json"
import lang_ru from "../../../desktop/locales/lang/ru.json"
import lang_tr from "../../../desktop/locales/lang/tr.json"
import lang_zhCN from "../../../desktop/locales/lang/zh-CN.json"
import lang_zhHK from "../../../desktop/locales/lang/zh-HK.json"
import lang_zhTW from "../../../desktop/locales/lang/zh-TW.json"
/**
 * This file is the language resource that is loaded in full when the app is initialized.
 * When switching languages, the app will automatically download the required language resources,
 * we will not load all the language resources to minimize the first screen loading time of the app.
 * Generally, we only load english resources synchronously by default.
 * In addition, we attach common resources for other languages, and the size of the common resources must be controlled.
 */
export const defaultResources = {
  en: {
    lang: lang_en,
    common: common_en,
    external: external_en,
    errors: errors_en,
  },
  "zh-CN": {
    lang: lang_zhCN,
    common: common_zhCN,
  },
  "zh-HK": {
    lang: lang_zhHK,
    common: common_zhHK,
  },

  ja: {
    lang: lang_ja,
    common: common_ja,
  },
  ru: { lang: lang_ru, common: common_ru },
  fi: { lang: lang_fi, common: common_fi },
  it: { lang: lang_it, common: common_it },
  "ar-DZ": { lang: lang_ardz, common: common_ardz },
  "ar-SA": { lang: lang_arsa, common: common_arsa },
  "ar-MA": { lang: lang_arma, common: common_arma },
  "zh-TW": { lang: lang_zhTW, common: common_zhTW },
  es: { lang: lang_es, common: common_es },
  fr: { lang: lang_fr, common: common_fr },
  pt: { lang: lang_pt, common: common_pt },
  "ar-IQ": { lang: lang_ariq, common: common_ariq },
  "ar-KW": { lang: lang_arkw, common: common_arkw },
  "ar-TN": { lang: lang_artn, common: common_artn },
  de: { lang: lang_de, common: common_de },
  ko: { lang: lang_ko, common: common_ko },
  tr: { lang: lang_tr, common: common_tr },
}
