// This file is generated by `pnpm run meta`
import i1 from "../client/pages/(main)/share/feeds/[id]/metadata"
import i2 from "../client/pages/(main)/share/lists/[id]/metadata"
import i0 from "../client/pages/(main)/share/users/[id]/metadata"

export default {
  "/share/users/:id": i0,
  "/share/feeds/:id": i1,
  "/share/lists/:id": i2,
}
