// This file is generated by `pnpm run meta`
import i0 from ".././client/pages/(login)/login/metadata"
import i3 from ".././client/pages/(main)/share/feeds/[id]/metadata"
import i2 from ".././client/pages/(main)/share/lists/[id]/metadata"
import i1 from ".././client/pages/(main)/share/users/[id]/metadata"

export default {
  "/login": i0,
  "/share/users/:id": i1,
  "/share/lists/:id": i2,
  "/share/feeds/:id": i3,
}
