on:
  pull_request:
  push:
    branches: [main, dev]

name: CI Format, Typecheck and Lint
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Format, Lint and Typecheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Format, Lint and Typecheck
        run: |
          pnpm run format:check
          pnpm run typecheck
          pnpm run lint
      - name: Run test
        run: pnpm test
