on:
  pull_request:
  push:
    branches: [main]

name: CI Typecheck and Lint

jobs:
  build:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint and Typecheck

        run: |
          pnpm run typecheck
          npm run lint
      - name: Run test
        run: pnpm test
