export const MAX_SUBSCRIPTION_COUNT = 500
export const MAX_INBOX_COUNT = 3

export const MAX_TRIAL_USER_FEED_SUBSCRIPTION = 5
export const MAX_TRIAL_USER_LIST_SUBSCRIPTION = 5
export const MAX_TRIAL_USER_INBOX_SUBSCRIPTION = 1
